spring.application.name=zosh-pos-system
# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/pos
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=create
